### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by an-rahulpandey** [PeterHdd/cordova-plugin-crypto-file#1]
I get net:ERR_CONNECTION_REFUSED (http://localhost:9800/index.html).

I am using the latest webview plugin and changed the port number to use 9800 instead of default. I also modified prepare hook to reflect  the changes.

**Comment by PeterHdd** [comment]
Can you please show me the changes that you did? If you change the port in the webview plugin, you need to change the port in the java file and the js file of the cordova-plugin-crypto-file.

Please show the changes so I know what you did, currently you cannot change the port of cordova-plugin-crypto-file from the plugin.xml of it.

**Comment by an-rahulpandey** [comment]
I have solved it, I have to modify the url in java file too. I have made the changes at this location, just changed the port to 9800 -

https://github.com/PeterHdd/cordova-plugin-crypto-file/blob/master/hooks/after_prepare.js#L72

https://github.com/PeterHdd/cordova-plugin-crypto-file/blob/master/src/android/com/crypt/cordova/DecryptResource.java#L27

I think we can make the port dynamic, because latest webview plugin allow us to change the port number.

**Comment by PeterHdd** [comment]
yup changing it in both java and js to make it the same as the webview plugin will fix the isssue.

I will try to update the plugin today or tomorrow, so you can update the port through the plugin.xml the same as the ionic webview plugin.xml.

Please star this plugin to support me!

**Comment by an-rahulpandey** [comment]
Great! Thanks.

**Comment by PeterHdd** [comment]
I have updated the plugin, in the latest version 1.2.0, you can change the port.
Please check the [Configuration section](https://github.com/PeterHdd/cordova-plugin-crypto-file#configuration)

Note: the port needs to be the same as the one of ionic webView.

**Comment by gaguerrero** [comment]
I run into the same error, I am using cordova 9.0.0 and ionic webkview plugin. Might you help me?

**Comment by SumeetHindinkeri** [comment]
@PeterHdd  I am facing same issue. Also I am not setting any WKPort value in config.xml

Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.6.3
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 32 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run                             : 1.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/sumeet.hindinkeri/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.2
   NodeJS            : v14.15.1 (/usr/local/bin/node)
   npm               : 6.14.8
   OS                : macOS Big Sur
   Xcode             : Xcode 12.4 Build version 12D4e
