### ISSUE TITLE
Decrypt not work - CordovaAndroid@7.1.4

### ISSUE THREAD

**Issue by QuasarX** [PeterHdd/cordova-plugin-crypto-file#4]
When i try to run the apk file its showing the encrypted data rather than opening the app.
I used "cordova-plugin-crypto-file v1.2.1" with Cordova CLI 8.1.2 (v1.4.0 - Latest version not work with CLI 8.1.2)

Also "tkyaji/cordova-plugin-crypt-file" have same issue.

(I don't use Ionic framework)

**Comment by PeterHdd** [comment]
>(I don't use Ionic framework)

What are you using?

**Comment by QuasarX** [comment]
Cordova CLI 8.1.2 for Construct 2 Game Engine

**Comment by QuasarX** [comment]
Solved: add this in config.xml and work
`<content src="index.html" />`

**Comment by PeterHdd** [comment]
closing this issue, now that it is fixed!
