### ISSUE TITLE
Cannot fetch data from server

### ISSUE THREAD

**Issue by larzaleth** [PeterHdd/cordova-plugin-crypto-file#6]
Hello, thank you for making this plugin.

Im using cordova 9 and worked perfectly in encrypting my sc

But another problem reached: my apps cannot fetching data from my hosting server after using this encryption plugin, its worked perfectly fine if i not using this plugin

please help

**Comment by PeterHdd** [comment]
Are you using cordova ionic webview?

**Comment by larzaleth** [comment]
nope, im using phonegap

**Comment by PeterHdd** [comment]
havent used phonegap, but if you are using a hosting server then you need to change the server of this plugin.

Cant change now, but try doing the following:

**In hook.js:**

```
            var port    = cfg.getGlobalPreference("cryptoPort");
            var server = cfg.getGlobalPreference("server");
            if( port == '' || server == '')
            {
                cfg.doc.getroot().getchildren().filter(function(child, idx, arr) {
                    return (child.tag == 'content');
                }).forEach(function(child) {
                    child.attrib.src = 'http://localhost:8080/' + child.attrib.src;
                });
            }
            else
            {
                cfg.doc.getroot().getchildren().filter(function(child, idx, arr) {
                    return (child.tag == 'content');
                }).forEach(function(child) {
                    child.attrib.src = server + port + '/' + child.attrib.src;
                });
            }
```

**DecryptResource.java:**

```
    public void changingPort(CordovaPreferences preferences){
    String port          = preferences.getString("cryptoPort","8080");
   String server       = preferences.getString("server","http://localhost:");
    URL_PREFIX       = server + port + "/";
  }
```

**config.xml:**

```
<preference name="cryptoPort" value="8080" />
<preference name="server" value="http://localhost:" />

Note: replace the value `value="http://localhost:"` in the config.xml with your hosting server.

Inform me after you do the changes.

**Comment by larzaleth** [comment]
Hello, 

After doing what you have told me, my app now get black blank screen after splash screen and showing this error: 

- application error: the connection to the server was unsuccessfull (http://hostserver.com:8080/index.html)
- application error: net:: ERR_CONNECTION_TIMED_OUT (http://hostserver.com:8080/index.html)

Already try adding cordova ionic webview plugin and configure it in config.xml, still getting that error

Already freshly create apps and running it without your plugin: problem solved. Then adding your plugin after that: show same error like above 

I will explain it in detail this time: 

Your plugin working perfectly in encrypt my source code and decrypt it when i install after building it in cordova cli. every page is showing perfectly

Then i have some slider whose data is fetching from my hosting server using ajax, it always return error: cannot fetch it from my hosting server

Why is that?

**Comment by PeterHdd** [comment]
I'm not sure, this plugin is only used to encrypt source code before running the app. If other pages are opening correctly then there should be no problem..

Can you try to remove it and add ionic webview plugin and test it

**Comment by larzaleth** [comment]
Just remove your plugin, it worked perfectly fetching data from my hosting server. 

Then add ionic webview plugin: it cannot fetch my data again from web server

**Comment by PeterHdd** [comment]
Okay, so we ionic webview alone also it doesn't work.

As a test change your server to localhost(your computer) and retrieve data from there

**Comment by larzaleth** [comment]
not working too

http://localhost/webserver/slider/get_json_slider **or** http://127.0.0.1/webserver/slider/get_json_slider

check in web browser it showing the data

**Comment by larzaleth** [comment]
Sorry its working when i test it to fetch from localhost
