### ISSUE TITLE
Not able to load the local resources

### ISSUE THREAD

**Issue by Virendrabaskar** [PeterHdd/cordova-plugin-crypto-file#7]
Hi,

When I use the plugin, My application was not able to load the local resources that are created dynamically on a Cache folder.

It may be because of the content policy.  I see that this plugin serve the decrypted sources on a http localhost with the configured port.

I wonder what if the configured port has been already used by different application ?
Also What happens If the port can listened by browsers, will the application render on the browsers ?

**Comment by bhushanpd** [comment]
Hi,

I am also facing the same issue on Android. I am trying to load the downloaded resources from cache folder and I am getting error as (http://localhost/_app_file_/data/user/0/com.****.***/cache/contactImages/WSi7wIMG-20190602-WA0002.jpg)  **net::ERR_CONNECTION_REFUSED**. I am using ionic web view 4.0.1, Android SDK target to 28.

Knidly, find below code I am using to read the local file.
 **$scope.getImagePath = function(item) {
                var str = cordova.file.cacheDirectory;
                var imgPath = str + "contactImages/"+ item.FileName + item.Extension;
                 return window.Ionic.WebView.convertFileSrc(imgPath);
          };**

Without cordova-plugin-crypto-file this source code is working perfectly fine.
 Kindly, look into this issue and please suggest solution for the same.

**Comment by PeterHdd** [comment]
@bhushanpd add your code in a repository and the steps that you are doing so I can try it and test it

**Comment by fdmartins** [comment]
The problem is the change in shouldInterceptRequest. 

Using super.shouldInterceptRequest we are not using localServer with local file implements in WebViewLocalServer.java :/

**Comment by PeterHdd** [comment]
@fdmartins can I contact you by email?

**Comment by fdmartins** [comment]
@PeterHdd of course yes

**Comment by fdmartins** [comment]
I found a solution for this issue.

In angular we need to convert uri to http using this command:
```
image = window.Ionic.WebView.convertFileSrc(imageUri);
```
In IonicWebViewEngine.java change to:

```
@Override
public WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest request) {
WebResourceResponse r = localServer.shouldInterceptRequest(request.getUrl(), request);

if (r==null)
{
     return super.shouldInterceptRequest(view, request);
}

return r;
}
```

and in WebViewLocalServer.java change line 231 returning null.

```
if (isLocalFile(uri) || uri.getAuthority().equals(this.authority)) {
Log.d("SERVER", "Handling local request: " + uri.toString());
return handleLocalRequest(uri, handler, request);
} else {
**//return handleProxyRequest(uri, handler);
return null;   // <<<<<<<--- HERE**
}

```

**Comment by bhushanpd** [comment]
@fdmartins Thanks a lot.. It worked perfectly...

**Comment by fdmartins** [comment]
@bhushanpd great!
