### ISSUE TITLE
Fails to trigger deviceReady for android kitkat, lollipop and marshmallow after the update.

### ISSUE THREAD

**Issue by bmunjal1990** [PeterHdd/cordova-plugin-crypto-file#8]
With the plugin updated to the latest version on cordova 9 it is failing to trigger deviceready event of cordova for android kitkat, lollipop, and marshmallow. Works fine for the versions above 6.0

**Comment by PeterHdd** [comment]
What other plugins are you using and what are the versions of the plugins ?

**Comment by bmunjal1990** [comment]
Thank you for your fast reply. These are all the plugins I am using:
cordova-admob-sdk 0.20.3 "AdMob SDK"
cordova-plugin-admob-free 0.22.0 "Cordova AdMob Plugin"
cordova-plugin-crypto-file 1.2.1 "Crypt File"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"

**Comment by PeterHdd** [comment]
If you are not using ionic webview plugin then just use the following plugin instead:

https://github.com/tkyaji/cordova-plugin-crypt-file

Also latest version of  cordova-plugin-crypto-file is 1.4

**Comment by bmunjal1990** [comment]
So this plugin (https://github.com/tkyaji/cordova-plugin-crypt-file) throws me this error `Using "requireCordovaModule" to load non-cordova module "path" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.`

Also, I updated cordova-plugin-crypto-file is 1.4.0 but I seem to have the same issue of deviceReady event not being fired.

I am gonna try to find if there is any plugin on my end that is creating an issue in conjunction with crypto plugin.

As for the other plugin you recommended me - doesn't seem like that it has been updated for cordova 9 yet.

**Comment by PeterHdd** [comment]
To solve that error, go to after_prepare.js and change the code to use require:

```

module.exports = function(context) {

    var path              = require('path'),
        fs                = require('fs'),
        crypto            = require('crypto'),
        Q                 = require('q'),
        cordova_util      = context.requireCordovaModule('cordova-lib/src/cordova/util'),
        platforms         = context.requireCordovaModule('cordova-lib/src/platforms/platforms'),
        ConfigParser      = context.requireCordovaModule('cordova-common').ConfigParser;
```

**Comment by bmunjal1990** [comment]
Seems to be getting very close in making it run as now the plugin runs but the build fails on this plugin with this error `ENOENT: no such file or directory, open \platforms\android\src\com\tkyaji\cordova\DecryptResource.java'`

**Comment by PeterHdd** [comment]
What version of cordova-android are u using?

**Comment by bmunjal1990** [comment]
Android version = android 8.0.0
AND
cordova --version = 9.0.0

**Comment by PeterHdd** [comment]
Copy all the after_prepare.js of this plugin into your file in the directory

**Comment by PeterHdd** [comment]
Also under platforms do you have the following folders:

```
platforms/android/src/
```

Or do you have:

```
platforms/android/app/src/
```

**Comment by bmunjal1990** [comment]
Will do that too. 
What I just did as I was comparing files of these 2 plugins - In the android case I replaced this line `var pluginDir = path.join(platformPath, 'src');` with the following line `var pluginDir = path.join(platformPath, 'app/src/main/java');` and it started to work after encryption on Android 6 marshmallow. 

I am gonna do some more tests and will keep you posted on its scope of resolution.

As for your last posted comment. I have the following folder hierarchy structure - platforms/android/app/src/

**Comment by PeterHdd** [comment]
The other plugin works only if you are using cordova-android@7 and above.

In this plugin in after_prepare.js I added support for both cordova-android@6 and below and crodova-android@7 and above.

In your code you are using cordova-android@6 as in the 7th version the directory changed and that's why you got that error.

You can specify the version by doing

```
ionic cordova platform add android@7

```

**Comment by PeterHdd** [comment]
Now that you are using the other plugin is deviceready getting triggered?

**Comment by bmunjal1990** [comment]
Yup, after making the changes as I described above - it is working for me on android - 6 device as well as on 8.1. I am gonna do few more tests on the 7.1 and 5.1 versions as well.

**Comment by PeterHdd** [comment]
Did it work on android kitkat, lollipop and marshmallow?

**Comment by bmunjal1990** [comment]
Sorry for the delay in response. I ran into some unrelated node.js error after doing some add and removing of the platforms so took me a while to get ready back again for testing.
YES, after doing changes as I described above (in the crypt plugin file) - I was successfully able to run the app on the following android versions:
kitkat, lollipop, marshmallow, and oreo.
